import { reportViewer } from "./viewer-client.js";

const css = `
:root { color-scheme: light; font-family: "Segoe UI", "Yu Gothic UI", sans-serif; color: #24343f; background: #f6f8f9; line-height: 1.55; overflow-wrap: anywhere; }
* { box-sizing: border-box; } body { margin: 0; } button, select, input { font: inherit; } button, select { cursor: pointer; }
body > header { background: #fff; border-top: 4px solid #19776b; border-bottom: 1px solid #dfe6e9; padding: 1rem max(1.5rem, calc((100vw - 1180px)/2)); }
h1 { font-size: 1.6rem; letter-spacing: -.02em; margin: 0 0 .25rem; } body > header p { margin: 0; color: #586b77; font-size: .82rem; }
main { max-width: 1236px; margin: auto; padding: 1.1rem 1.75rem 3rem; } h2 { font-size: 1.1rem; margin: 0 0 .75rem; } h3 { font-size: 1rem; }
section { margin: 1rem 0; padding: 1.25rem; border: 1px solid #dfe6e9; background: white; border-radius: 12px; min-width: 0; }
p, dd, code, summary, .row-content, .field { overflow-wrap: anywhere; } p { margin: .65rem 0; } .muted, small { color: #586b77; font-size: .82rem; }
.section-heading { display: flex; flex-wrap: wrap; justify-content: space-between; align-items: baseline; gap: .35rem 1rem; margin-bottom: .85rem; } .section-heading h2, .section-heading p { margin: 0; }
.report-meta { display: flex; flex-wrap: wrap; gap: .5rem; align-items: center; } .report-meta > strong { flex: 1 1 220px; overflow-wrap: anywhere; font: .78rem/1.6 Consolas, monospace; color: #586b77; }
.generation-notice { margin: 1rem 0; padding: 1rem; border: 1px solid #dbc594; border-left: 3px solid #ad7d27; border-radius: 6px; background: #fff9ec; } .generation-notice p { margin: .4rem 0; } .generation-notice button { font-size: .82rem; margin-top: .35rem; }
.badge { display: inline-block; border: 1px solid #c4d2cd; border-radius: 6px; font-size: .78rem; line-height: 1.4; padding: .25rem .5rem; background: #f1f5f3; white-space: normal; }
.badge[data-tone="good"] { background: #e0f2e8; color: #125039; border-color: #acd3bb; } .badge[data-tone="bad"] { background: #fff0eb; color: #963e29; border-color: #e9beae; }
.summary-cards { display: grid; grid-template-columns: repeat(4,minmax(0,1fr)); gap: .75rem; } .summary-card { display: grid; grid-template-columns: minmax(0,1fr) auto; align-items: center; gap: .2rem .5rem; background: #fafcfc; border: 1px solid #e2e8eb; padding: .8rem 1rem; border-radius: 8px; }
.summary-card > .badge { justify-self: start; } .summary-card > strong { grid-column: 2; grid-row: 1 / 3; font-size: 2rem; font-weight: 600; line-height: 1.2; font-variant-numeric: tabular-nums; }
.summary-card > small { grid-column: 1; } .summary-facts { display: grid; grid-template-columns: repeat(4,minmax(0,1fr)); gap: .65rem 1.5rem; margin: 1rem 0; } dt { color: #586b77; font-size: .8rem; } dd { margin: .25rem 0 0; white-space: pre-wrap; }
.summary-facts .field { display: flex; flex-wrap: wrap; align-items: baseline; gap: .3rem; justify-content: space-between; } .summary-facts dd { margin: 0; font-size: 1.05rem; font-weight: 600; }
.notice { padding: .6rem .75rem; background: #f4f7f8; border-left: 3px solid #859caa; font-size: .8rem; } .summary-more { padding: .6rem 0; } .summary-more > summary { color: #17685a; }
section > .notice:last-child { margin: .4rem 0 0; }
.filters { display: grid; grid-template-columns: repeat(4,minmax(0,1fr)); gap: .65rem .85rem; align-items: end; padding: .8rem 0; border-top: 1px solid #e4e9ec; border-bottom: 1px solid #e4e9ec; }
label { display: flex; flex-direction: column; gap: .3rem; font-size: .8rem; color: #586b77; min-width: 0; } select, input, button { border: 1px solid #b9c8cf; border-radius: 6px; background: white; color: #24343f; padding: .45rem .65rem; max-width: 100%; }
input { min-width: 160px; } button:hover { background: #eaf3ee; } button:disabled { cursor: default; opacity: .5; } :focus-visible { outline: 3px solid #216eaf; outline-offset: 3px; }
.filter-actions { display: flex; flex-wrap: wrap; gap: .4rem .6rem; align-items: center; justify-content: space-between; min-width: 0; } .filter-actions button { font-size: .82rem; } .zone { font-size: .75rem; color: #586b77; }
.items { display: grid; gap: .6rem; } .result-row { display: flex; align-items: center; gap: .85rem; text-align: left; width: 100%; padding: .85rem 1rem; border-color: #dfe6e9; } .result-row:hover { border-color: #91b7af; }
.result-row > .badge { flex: 0 0 76px; text-align: center; } .row-content { flex: 1; min-width: 0; display: grid; gap: .2rem; } .result-row > small { flex: 0 1 200px; text-align: right; }
.row-message { display: -webkit-box; -webkit-box-orient: vertical; -webkit-line-clamp: 2; overflow: hidden; white-space: pre-wrap; font-size: .88rem; color: #445966; } .row-content > strong { font-weight: 600; }
.pager { display: flex; flex-wrap: wrap; gap: .75rem; justify-content: center; align-items: center; margin-top: 1rem; font-size: .8rem; } .empty { padding: 2rem 1rem; text-align: center; background: #f6f8f6; }
dialog { --detail-padding: 1.5rem; width: min(940px, calc(100vw - 32px)); max-height: calc(100vh - 32px); border: 1px solid #d0dce2; border-radius: 14px; padding: var(--detail-padding); color: #24343f; box-shadow: 0 24px 80px #172f4333; } dialog::backdrop { background: #192f4380; }
.detail-toolbar { position: sticky; top: calc(-1 * var(--detail-padding)); z-index: 2; display: flex; justify-content: flex-end; margin: calc(-1 * var(--detail-padding)) calc(-1 * var(--detail-padding)) 1rem; padding: .65rem var(--detail-padding); background: #fff; border-bottom: 1px solid #dfe6e9; } dialog > .badge { margin-right: .5rem; } .details-grid { display: grid; grid-template-columns: repeat(2,minmax(0,1fr)); gap: 1rem; }
.message-field { grid-column: 1 / -1; padding: 1rem; background: #f6f8f9; border-left: 3px solid #93b4ae; border-radius: 0 6px 6px 0; } .message-field dd { line-height: 1.7; }
.media-jump { display: block; margin-top: .85rem; } dialog h2 { scroll-margin-top: 5rem; }
.video-controls { display: none; } .video-controls input { min-width: 0; width: 100%; height: 40px; padding: 0; accent-color: #19776b; } .video-controls button { width: 100%; margin: 0; } .video-controls small { font-variant-numeric: tabular-nums; }
.image-viewport { margin: .7rem 0; } .image-viewport img { margin: 0; } .image-viewport img:not(.expanded) { max-height: min(65vh, 340px); }
.step-workspace { display: grid; grid-template-columns: 250px minmax(0,1fr); gap: 1rem; align-items: start; } .step-workspace > section { margin: 0; min-width: 0; padding: 1rem; max-height: 62vh; overflow: auto; }
.step-list > .muted { font-size: .75rem; } .step-choice { display: grid; grid-template-columns: auto minmax(0,1fr); width: 100%; text-align: left; border: 1px solid #dce5e8; border-left: 3px solid #b6d3c5; gap: .3rem .6rem; } .step-choice[aria-pressed="true"] { background: #e6f3ef; border-color: #19776b; } .step-choice .badge { justify-self: start; grid-column: 2; } .step-choice small { grid-column: 2; margin: 0; }
.step-summary h3 { margin: 0 0 .45rem; font-size: 1.05rem; scroll-margin-top: 5rem; } .step-summary .step-message { margin: .55rem 0; white-space: pre-wrap; } .step-nav { display: flex; flex-wrap: wrap; gap: .4rem; margin: .75rem 0; } .step-nav button { font-size: .8rem; }
.primary-message { margin: .6rem 0 1rem; } .primary-message .message-field { padding: .6rem .8rem; } .primary-message dd { max-height: 5rem; overflow: auto; } .technical-details { margin-top: 1rem; } .detail-toolbar { justify-content: space-between; gap: .5rem; flex-wrap: wrap; } .detail-toolbar .media-jump { margin: 0; } dialog { width: min(1180px, calc(100vw - 32px)); }
.detail-heading { display: flex; align-items: center; flex-wrap: wrap; gap: .5rem; } .detail-heading h2 { margin: 0; margin-right: auto; } .media-heading { display: flex; align-items: center; justify-content: space-between; gap: .5rem; flex-wrap: wrap; } .media-heading h3 { margin: 0; font-size: .85rem; } .media-card { padding: .75rem; } .media-info { margin-top: .5rem; padding: .45rem 0 0; }
.step-evidence > h2 { font-size: .9rem; color: #586b77; margin-bottom: .65rem; } .step-evidence .image-viewport img:not(.expanded) { max-height: min(40vh, 300px); } .step-evidence > div > .muted { margin: .35rem 0; } .step-nav { margin: .5rem 0; }
.step-summary { display: flex; flex-wrap: wrap; align-items: center; gap: .3rem .5rem; } .step-summary h3 { flex: 1; margin-bottom: 0; } .step-summary .step-message { flex-basis: 100%; margin: .35rem 0; } .image-viewport img:not(.expanded) { margin-inline: auto; }
@media (min-width: 801px) { .step-evidence .image-viewport img:not(.expanded) { max-height: clamp(140px, calc(62vh - 220px), 300px); } }
@media (max-width: 800px) { .step-workspace { grid-template-columns: minmax(0,1fr); } .step-workspace > .step-list { max-height: 16rem; } .step-workspace > .step-evidence { max-height: none; overflow: visible; } .detail-toolbar button { font-size: .8rem; } }
.timeline-item { display: flex; align-items: center; flex-wrap: wrap; gap: .6rem; border-left: 2px solid #b6d3c5; padding: .6rem; background: #f7faf8; } .timeline-item small { margin-left: auto; }
.coverage-item { border-bottom: 1px solid #dde5df; padding: .75rem 0; } .media-card { border: 1px solid #d9e2dc; border-radius: 8px; padding: 1rem; min-width: 0; } .media-card a, .media-card button { display: inline-block; margin: .5rem .7rem .2rem 0; } a { color: #17685a; }
img, video { display: block; max-width: 100%; max-height: 340px; object-fit: contain; margin: .7rem 0; } .image-viewport { max-width: 100%; max-height: min(65vh, 720px); overflow: auto; } img.expanded { max-height: none; max-width: none; width: auto; min-width: 100%; } details { border-top: 1px solid #d9e2dc; padding: .8rem 0; } summary { cursor: pointer; font-size: .85rem; }
@media (max-width: 650px) { main { padding: 1rem .65rem 3rem; } body > header { padding: 1.1rem 1rem; } h1 { font-size: 1.35rem; } section { padding: 1rem; } .summary-cards, .summary-facts, .filters { grid-template-columns: repeat(2,minmax(0,1fr)); } .summary-card { padding: .75rem; } .details-grid { grid-template-columns: 1fr; } input { min-width: 0; width: 100%; } .result-row { flex-wrap: wrap; padding: .8rem; } .result-row > small { flex-basis: 100%; text-align: left; } .result-row > .badge { flex-basis: auto; } .row-content { flex-basis: 100%; } dialog { --detail-padding: 1rem; } }
@media print { body, main { background: white; } body > header { background: white; color: #24343f; } body > header p { color: #586b77; } .filters, button, .pager { display: none; } section { break-inside: avoid; } }
@media (max-width: 320px) { .summary-cards, .summary-facts, .filters { grid-template-columns: 1fr; } .report-meta > strong { min-width: 0; } dialog { --detail-padding: .5rem; width: calc(100vw - 16px); max-width: calc(100vw - 16px); } dialog section { padding: .5rem; margin: .8rem 0; } .step-workspace > section { padding: .5rem; } .media-card, .message-field { padding: .5rem; } .media-card button { margin-right: 0; } .video-controls { display: grid; gap: .3rem; } }
`;

export function getReportRenderer(): { css: string; js: string } {
  return { css, js: '"use strict";\n(' + reportViewer.toString() + ')();\n' };
}
